# Generated by Django 4.1.5 on 2023-04-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_employees_user_leaverequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
