# Generated by Django 4.1.5 on 2023-04-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_leaverequest_is_approved_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
    ]
